apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template: # pod template
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: bakcend
          image: weyouth/backend
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
              name: api
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quest
spec:
  selector:
    matchLabels:
      app: quest
  replicas: 3
  template:
    metadata:
      labels:
        app: quest
    spec:
      containers:
        - name: quest
          image: weyouth/quest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8983
---
apiVersion: v1
kind: Service
metadata:
  name: quest
spec:
  selector:
    app: quest
  ports:
    - port: 8983
      targetPort: 8983
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
    - name: mysql
      image: weyouth/mysql
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootpass
        - name: MYSQL_DATABASE
          value: youthchina
      volumeMounts:
        - name: mysql-data
          mountPath: /home/zhongyangwu/code/docker/volumes/weyouth/mysql
  volumes:
    - name: mysql-data
      hostPath:
        path: /home/zhongyangwu/code/docker/volumes/weyouth/mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: weyouth/rabbitmq
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 15672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - port: 15672
      targetPort: 15672
